<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MeziantouAnalysisMode>all-warnings</MeziantouAnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Krafs.Publicizer" Version="2.3.2" />
    <PackageVersion Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageVersion Include="Lib.Harmony" Version="2.4.2" />
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.156" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="NUnit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.32.0.713" />
  </ItemGroup>
</Project>