<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Krafs.Publicizer" Version="2.3.2" />
    <PackageVersion Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageVersion Include="Lib.Harmony" Version="2.4.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageVersion Include="NUnit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>
</Project>
